name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        echo "Creating virtual environment..."
        python -m venv venv
        echo "Activating virtual environment..."
        source venv/bin/activate
        echo "Installing dependencies..."
        pip install -r requirements.txt

    - name: Install Heroku CLI
      run: |
        echo "Installing Heroku CLI..."
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Verify Heroku CLI Installation
      run: heroku --version

    - name: Authenticate Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "Authenticating with Heroku..."
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_API_KEY" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login $HEROKU_API_KEY" >> ~/.netrc
        heroku auth:token

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        echo "Setting Heroku remote..."
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME 
}}.git
        echo "Pushing to Heroku..."
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ 
secrets.HEROKU_APP_NAME }}.git HEAD:main

